'use strict';

module.exports = {
  up: async (queryInterface, Sequelize) => {
    await queryInterface.sequelize.query('ALTER SEQUENCE "Lists_id_seq" RESTART WITH 1');

    return queryInterface.bulkInsert('Lists', [
      {
        userId: 1,
        name: 'My Favorites',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        userId: 2,
        name: 'My Favorites',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        userId: 3,
        name: 'My Favorites',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        userId: 4,
        name: 'My Favorites',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        userId: 5,
        name: 'My Favorites',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        userId: 6,
        name: 'My Favorites',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        userId: 7,
        name: 'My Favorites',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        userId: 8,
        name: 'My Favorites',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        userId: 9,
        name: 'My Favorites',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        userId: 10,
        name: 'My Favorites',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        userId: 11,
        name: 'My Favorites',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        userId: 12,
        name: 'My Favorites',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        userId: 13,
        name: 'My Favorites',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        userId: 14,
        name: 'My Favorites',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        userId: 15,
        name: 'My Favorites',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        userId: 16,
        name: 'My Favorites',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        userId: 17,
        name: 'My Favorites',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        userId: 18,
        name: 'My Favorites',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        userId: 19,
        name: 'My Favorites',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        userId: 20,
        name: 'My Favorites',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        userId: 21,
        name: 'My Favorites',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        userId: 22,
        name: 'My Favorites',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        userId: 23,
        name: 'My Favorites',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        userId: 24,
        name: 'My Favorites',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        userId: 25,
        name: 'My Favorites',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        userId: 26,
        name: 'My Favorites',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        userId: 27,
        name: 'My Favorites',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        userId: 28,
        name: 'My Favorites',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        userId: 29,
        name: 'My Favorites',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        userId: 30,
        name: 'My Favorites',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        userId: 31,
        name: 'My Favorites',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        userId: 32,
        name: 'My Favorites',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        userId: 33,
        name: 'My Favorites',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        userId: 34,
        name: 'My Favorites',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        userId: 35,
        name: 'My Favorites',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        userId: 36,
        name: 'My Favorites',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        userId: 37,
        name: 'My Favorites',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        userId: 38,
        name: 'My Favorites',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        userId: 39,
        name: 'My Favorites',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        userId: 40,
        name: 'My Favorites',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        userId: 41,
        name: 'My Favorites',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        userId: 42,
        name: 'My Favorites',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        userId: 43,
        name: 'My Favorites',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        userId: 44,
        name: 'My Favorites',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        userId: 45,
        name: 'My Favorites',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        userId: 46,
        name: 'My Favorites',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        userId: 47,
        name: 'My Favorites',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        userId: 48,
        name: 'My Favorites',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        userId: 49,
        name: 'My Favorites',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        userId: 50,
        name: 'My Favorites',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        userId: 51,
        name: 'My Favorites',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        userId: 52,
        name: 'My Favorites',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ]);
  },

  down: async (queryInterface, Sequelize) => {
    return queryInterface.bulkDelete('Lists', null, {});
  },
};
