const Tags = [
  'Dogs on leash',
  'Kid friendly',
  'Hiking',
  'Walking',
  'Running',
  'Forest',
  'River',
  'Views',
  'Wild flowers',
  'Wildlife',
  'Muddy',
  'Fee',
  'Nature trips',
  'Cave',
  'Waterfall',
  'Fishing',
  'Mountain biking',
  'Dog friendly',
  'Bugs',
  'Rocky',
  'Bird watching',
  'Over grown',
  'Wheelchair friendly',
  'Stroller friendly',
  'Road biking',
  'Lake',
  'Partially paved',
  'Paved',
  'Beach',
  'City walk',
  'No dogs',
  'Historic site',
  'Rock climbing',
  'Blowdown',
  'No shade',
  'Scramble',
  'Horseback riding',
  'Rails trails',
  'Snowshoeing',
  'Off trail',
  'Backpacking',
  'Snow',
  'Paddle sports',
  'Bike touring',
  'Ohv / off road driving',
  'Washed out',
  'Bridge out',
  'Camping',
  'Closed',
  'Cross country skiing',
  'Skiing',
];
export default Tags;
